#!/bin/bash
# Quick Reference Guide for Dotfiles Configuration Manager v2.1.3

echo "Dotfiles Configuration Manager v2.1.3 - Quick Reference"
echo "========================================================="
echo ""
echo "BASIC USAGE:"
echo "  ./installer.sh                             # Standard installation"
echo "  ./installer.sh --dry-run                   # Preview only"
echo "  ./installer.sh --help                      # Show help"
echo ""
echo "INSTALLATION (7 Phases):"
echo "  1. Back up existing configs to ~/.config_backup-<timestamp>/"
echo "  2. Copy project to ~/.lnx-config/ (including .git)"
echo "  3. Create required directories (bash, vim, etc)"
echo "  4. Install ~/.bashrc and ~/.vimrc with proper sourcing"
echo "  5. Create configuration symlinks (ranger, joshuto, mpv)"
echo "  6. Set permissions on scripts and configs"
echo "  7. Initialize git commit with all changes"
echo ""
echo "FILE LOCATIONS:"
echo "  ~/.lnx-config/                        # Main installation directory"
echo "  ~/.lnx-config/configs/bash/main.sh    # Bash configuration entry point"
echo "  ~/.lnx-config/configs/vim/            # Vim configuration directory"
echo "  ~/.bashrc                             # Sources ~/.lnx-config/configs/bash/main.sh"
echo "  ~/.vimrc                              # Sources ~/.lnx-config/configs/vim/"
echo ""
echo "SYMLINKS (Auto-created during installation):"
echo "  ~/.config/ranger    -> ~/.lnx-config/configs/ranger"
echo "  ~/.config/joshuto   -> ~/.lnx-config/configs/joshuto"
echo "  ~/.config/mpv       -> ~/.lnx-config/configs/mpv"
echo ""
echo "GIT WORKFLOW:"
echo "  cd ~/.lnx-config"
echo "  git status                            # Check changes"
echo "  git diff                              # View changes"
echo "  git add configs/bash/aliases/alias.sh # Stage changes"
echo "  git commit -m 'Updated aliases'       # Commit changes"
echo ""
echo "RESTORE FROM BACKUP:"
echo "  cp -r ~/.config_backup-<timestamp>/bash ~/.config/"
echo "  cp ~/.config_backup-<timestamp>/.bashrc ~/"
echo ""
echo "For full documentation, see docs/README.md"
