#!/bin/bash
# ============================================================================
# Bash Completion Configuration
# ============================================================================
# Central configuration for the completion system

# Performance settings
COMPLETION_CACHE_TTL=${COMPLETION_CACHE_TTL:-86400}  # 24 hours
COMPLETION_MAX_CACHE_SIZE=${COMPLETION_MAX_CACHE_SIZE:-1000}
COMPLETION_DEBUG=${COMPLETION_DEBUG:-0}
COMPLETION_LAZY_LOAD=${COMPLETION_LAZY_LOAD:-1}

# Enable/disable specific modules
COMPLETION_ENABLE_GIT=${COMPLETION_ENABLE_GIT:-1}
COMPLETION_ENABLE_DOCKER=${COMPLETION_ENABLE_DOCKER:-1}
COMPLETION_ENABLE_NPM=${COMPLETION_ENABLE_NPM:-1}
COMPLETION_ENABLE_SSH=${COMPLETION_ENABLE_SSH:-1}
COMPLETION_ENABLE_SYSTEMD=${COMPLETION_ENABLE_SYSTEMD:-1}

# Cache directory override
COMPLETION_CACHE_DIR=${COMPLETION_CACHE_DIR:-"${XDG_CACHE_HOME:-$HOME/.cache}/bash-completion"}

# Export configuration
export COMPLETION_CACHE_TTL COMPLETION_MAX_CACHE_SIZE COMPLETION_DEBUG
export COMPLETION_LAZY_LOAD COMPLETION_CACHE_DIR
export COMPLETION_ENABLE_GIT COMPLETION_ENABLE_DOCKER COMPLETION_ENABLE_NPM
export COMPLETION_ENABLE_SSH COMPLETION_ENABLE_SYSTEMD
