#!/bin/bash

# Guard against re-sourcing to prevent readonly variable conflicts
[[ -n "${__COLORS_SOURCED:-}" ]] && return 0
__COLORS_SOURCED=1

# Theme Colors (for bash prompt)
C_USER='\[\033[1;34m\]'      # Blue
C_HOST='\[\033[1;32m\]'      # Green  
C_IP='\[\033[1;35m\]'        # Magenta
C_PATH='\[\033[1;36m\]'      # Cyan
C_VENV='\[\033[1;33m\]'      # Yellow
C_BRANCH='\[\033[1;31m\]'    # Red
C_AHEAD='\[\033[1;33m\]'     # Yellow (ahead)
C_BEHIND='\[\033[1;32m\]'    # Green (behind)
C_COMMIT='\[\033[1;35m\]'    # Magenta (files to commit)
C_SYMBOL='\[\033[1;37m\]'    # White
C_RESET='\[\033[0m\]'        # Reset

# Regular Colors (for logging)
readonly COLOR_BLACK='\033[0;30m'
readonly COLOR_RED='\033[0;31m'
readonly COLOR_GREEN='\033[0;32m'
readonly COLOR_YELLOW='\033[0;33m'
readonly COLOR_BLUE='\033[0;34m'
readonly COLOR_MAGENTA='\033[0;35m'
readonly COLOR_CYAN='\033[0;36m'
readonly COLOR_WHITE='\033[0;37m'
readonly COLOR_PURPLE='\033[0;35m'  # Alias for MAGENTA

# Bold Colors
readonly COLOR_BOLD_BLACK='\033[1;30m'
readonly COLOR_BOLD_RED='\033[1;31m'
readonly COLOR_BOLD_GREEN='\033[1;32m'
readonly COLOR_BOLD_YELLOW='\033[1;33m'
readonly COLOR_BOLD_BLUE='\033[1;34m'
readonly COLOR_BOLD_MAGENTA='\033[1;35m'
readonly COLOR_BOLD_CYAN='\033[1;36m'
readonly COLOR_BOLD_WHITE='\033[1;37m'

# Underline Colors
readonly COLOR_UNDERLINE_BLACK='\033[4;30m'
readonly COLOR_UNDERLINE_RED='\033[4;31m'
readonly COLOR_UNDERLINE_GREEN='\033[4;32m'
readonly COLOR_UNDERLINE_YELLOW='\033[4;33m'
readonly COLOR_UNDERLINE_BLUE='\033[4;34m'
readonly COLOR_UNDERLINE_MAGENTA='\033[4;35m'
readonly COLOR_UNDERLINE_CYAN='\033[4;36m'
readonly COLOR_UNDERLINE_WHITE='\033[4;37m'

# Background Colors
readonly COLOR_BG_BLACK='\033[40m'
readonly COLOR_BG_RED='\033[41m'
readonly COLOR_BG_GREEN='\033[42m'
readonly COLOR_BG_YELLOW='\033[43m'
readonly COLOR_BG_BLUE='\033[44m'
readonly COLOR_BG_MAGENTA='\033[45m'
readonly COLOR_BG_CYAN='\033[46m'
readonly COLOR_BG_WHITE='\033[47m'

# High Intensity Colors
readonly COLOR_INTENSE_BLACK='\033[0;90m'
readonly COLOR_INTENSE_RED='\033[0;91m'
readonly COLOR_INTENSE_GREEN='\033[0;92m'
readonly COLOR_INTENSE_YELLOW='\033[0;93m'
readonly COLOR_INTENSE_BLUE='\033[0;94m'
readonly COLOR_INTENSE_MAGENTA='\033[0;95m'
readonly COLOR_INTENSE_CYAN='\033[0;96m'
readonly COLOR_INTENSE_WHITE='\033[0;97m'

# Bold High Intensity Colors
readonly COLOR_BOLD_INTENSE_BLACK='\033[1;90m'
readonly COLOR_BOLD_INTENSE_RED='\033[1;91m'
readonly COLOR_BOLD_INTENSE_GREEN='\033[1;92m'
readonly COLOR_BOLD_INTENSE_YELLOW='\033[1;93m'
readonly COLOR_BOLD_INTENSE_BLUE='\033[1;94m'
readonly COLOR_BOLD_INTENSE_MAGENTA='\033[1;95m'
readonly COLOR_BOLD_INTENSE_CYAN='\033[1;96m'
readonly COLOR_BOLD_INTENSE_WHITE='\033[1;97m'

# High Intensity Background Colors
readonly COLOR_BG_INTENSE_BLACK='\033[0;100m'
readonly COLOR_BG_INTENSE_RED='\033[0;101m'
readonly COLOR_BG_INTENSE_GREEN='\033[0;102m'
readonly COLOR_BG_INTENSE_YELLOW='\033[0;103m'
readonly COLOR_BG_INTENSE_BLUE='\033[0;104m'
readonly COLOR_BG_INTENSE_MAGENTA='\033[0;105m'
readonly COLOR_BG_INTENSE_CYAN='\033[0;106m'
readonly COLOR_BG_INTENSE_WHITE='\033[0;107m'

# Special formatting
readonly COLOR_BOLD='\033[1m'
readonly COLOR_DIM='\033[2m'
readonly COLOR_ITALIC='\033[3m'
readonly COLOR_UNDERLINE='\033[4m'
readonly COLOR_BLINK='\033[5m'
readonly COLOR_REVERSE='\033[7m'
readonly COLOR_HIDDEN='\033[8m'
readonly COLOR_STRIKETHROUGH='\033[9m'

# Reset/No Color
readonly NC='\033[0m'
readonly RESET='\033[0m'  # Alias for NC

# Aliases for common usage (backward compatibility)
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly MAGENTA='\033[0;35m'
readonly CYAN='\033[0;36m'
readonly WHITE='\033[0;37m'

# Special characters (ASCII safe versions)
readonly CHAR_CHECKMARK='✓ '
readonly CHAR_CROSS='✗ '
readonly CHAR_WARNING='! '
readonly CHAR_INFO='🛈 '
readonly CHAR_ARROW='→ '
readonly CHAR_BULLET='• '
readonly CHAR_STAR='[*]'
readonly CHAR_SQUARE='[■] '

# Export all colors for use in other scripts
export C_USER C_HOST C_IP C_PATH C_VENV C_BRANCH C_AHEAD C_BEHIND C_COMMIT C_SYMBOL C_RESET
export COLOR_BLACK COLOR_RED COLOR_YELLOW COLOR_GREEN COLOR_BLUE COLOR_MAGENTA COLOR_CYAN COLOR_WHITE COLOR_BOLD
export COLOR_BOLD_BLACK COLOR_BOLD_RED COLOR_BOLD_GREEN COLOR_BOLD_YELLOW COLOR_BOLD_BLUE COLOR_BOLD_MAGENTA COLOR_BOLD_CYAN COLOR_BOLD_WHITE
export COLOR_UNDERLINE_BLACK COLOR_UNDERLINE_RED COLOR_UNDERLINE_GREEN COLOR_UNDERLINE_YELLOW COLOR_UNDERLINE_BLUE COLOR_UNDERLINE_MAGENTA COLOR_UNDERLINE_CYAN COLOR_UNDERLINE_WHITE
export COLOR_BG_BLACK COLOR_BG_RED COLOR_BG_GREEN COLOR_BG_YELLOW COLOR_BG_BLUE COLOR_BG_MAGENTA COLOR_BG_CYAN COLOR_BG_WHITE
export COLOR_INTENSE_BLACK COLOR_INTENSE_RED COLOR_INTENSE_GREEN COLOR_INTENSE_YELLOW COLOR_INTENSE_BLUE COLOR_INTENSE_MAGENTA COLOR_INTENSE_CYAN COLOR_INTENSE_WHITE
export COLOR_BOLD_INTENSE_BLACK COLOR_BOLD_INTENSE_RED COLOR_BOLD_INTENSE_GREEN COLOR_BOLD_INTENSE_YELLOW COLOR_BOLD_INTENSE_BLUE COLOR_BOLD_INTENSE_MAGENTA COLOR_BOLD_INTENSE_CYAN COLOR_BOLD_INTENSE_WHITE
export COLOR_BG_INTENSE_BLACK COLOR_BG_INTENSE_RED COLOR_BG_INTENSE_GREEN COLOR_BG_INTENSE_YELLOW COLOR_BG_INTENSE_BLUE COLOR_BG_INTENSE_MAGENTA COLOR_BG_INTENSE_CYAN COLOR_BG_INTENSE_WHITE
export COLOR_DIM COLOR_ITALIC COLOR_UNDERLINE COLOR_BLINK COLOR_REVERSE COLOR_HIDDEN COLOR_STRIKETHROUGH
export NC RED GREEN YELLOW BLUE MAGENTA CYAN WHITE
export CHAR_CHECKMARK CHAR_CROSS CHAR_WARNING CHAR_INFO CHAR_ARROW CHAR_BULLET CHAR_STAR CHAR_SQUARE
